# Generated by Django 5.0.1 on 2024-03-10 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideReady_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otp_details',
            new_name='profile',
        ),
    ]
