# Generated by Django 5.0.1 on 2024-03-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideReady_app', '0002_rename_otp_details_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='lastName',
            new_name='mobile',
        ),
    ]
