# Generated by Django 5.0.1 on 2024-03-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideReady_app', '0003_rename_lastname_profile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
    ]
