# Generated by Django 5.0.1 on 2024-03-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideReady_app', '0004_remove_profile_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=15)),
                ('Occupation', models.CharField(max_length=100)),
            ],
        ),
    ]
