# Generated by Django 5.0.1 on 2024-03-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideReady_app', '0006_profile2'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exShowroomPrice', models.CharField(max_length=100)),
                ('initialPayment', models.CharField(max_length=150)),
                ('loanAmount', models.CharField(max_length=100)),
                ('loanApplicationDate', models.CharField(max_length=100)),
            ],
        ),
    ]
