# Generated by Django 5.0.1 on 2024-03-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideReady_app', '0007_profile3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profile1',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='accountNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='ifscCode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='zipCode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile3',
            name='exShowroomPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile3',
            name='initialPayment',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile3',
            name='loanAmount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile3',
            name='loanApplicationDate',
            field=models.DateField(),
        ),
    ]
